val x = 3
exception Bad = x
